# Generated by Django 6.1 on 2026-08-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('Diabetes', 'Diabetes'), ('Heart', 'Heart Disease'), ('Skin', 'Skin Cancer')], max_length=20)),
                ('result', models.CharField(max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
