# Generated by Django 6.1 on 2026-08-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictionrecord_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prediction_images/'),
        ),
    ]
